name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Run tests inside nix-shell
        run: |
          export NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-25.05.tar.gz
          nix-shell --pure --run '
            export NODE_EXTRA_CA_CERTS=$(find /nix/store -name ca-bundle.crt | head -n1)
            npm install
            npm test
          '

